name: bike-sharing-demand-forecasting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ipykernel
  - jupyterlab
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - statsmodels
  - pytorch
